export const countryCodes = [
  { code: "+1", label: "🇺🇸 United States" },
  { code: "+44", label: "🇬🇧 United Kingdom" },
  { code: "+91", label: "🇮🇳 India" },
  { code: "+61", label: "🇦🇺 Australia" },
  { code: "+81", label: "🇯🇵 Japan" },
  { code: "+49", label: "🇩🇪 Germany" },
  { code: "+33", label: "🇫🇷 France" },
  { code: "+39", label: "🇮🇹 Italy" },
  { code: "+86", label: "🇨🇳 China" },
  { code: "+971", label: "🇦🇪 United Arab Emirates" },
  { code: "+7", label: "🇷🇺 Russia / Kazakhstan" },
  { code: "+55", label: "🇧🇷 Brazil" },
  { code: "+27", label: "🇿🇦 South Africa" },
  { code: "+82", label: "🇰🇷 South Korea" },
  { code: "+34", label: "🇪🇸 Spain" },
  { code: "+64", label: "🇳🇿 New Zealand" },
  { code: "+31", label: "🇳🇱 Netherlands" },
  { code: "+47", label: "🇳🇴 Norway" },
  { code: "+46", label: "🇸🇪 Sweden" },
  { code: "+41", label: "🇨🇭 Switzerland" },
  { code: "+52", label: "🇲🇽 Mexico" },
  { code: "+48", label: "🇵🇱 Poland" },
  { code: "+36", label: "🇭🇺 Hungary" },
  { code: "+351", label: "🇵🇹 Portugal" },
  { code: "+420", label: "🇨🇿 Czech Republic" },
  { code: "+380", label: "🇺🇦 Ukraine" },
  { code: "+65", label: "🇸🇬 Singapore" },
  { code: "+60", label: "🇲🇾 Malaysia" },
  { code: "+66", label: "🇹🇭 Thailand" },
  { code: "+62", label: "🇮🇩 Indonesia" },
  { code: "+63", label: "🇵🇭 Philippines" },
  { code: "+92", label: "🇵🇰 Pakistan" },
  { code: "+880", label: "🇧🇩 Bangladesh" },
  { code: "+20", label: "🇪🇬 Egypt" },
  { code: "+212", label: "🇲🇦 Morocco" },
  { code: "+213", label: "🇩🇿 Algeria" },
  { code: "+216", label: "🇹🇳 Tunisia" },
  { code: "+254", label: "🇰🇪 Kenya" },
  { code: "+256", label: "🇺🇬 Uganda" },
  { code: "+234", label: "🇳🇬 Nigeria" },
  { code: "+58", label: "🇻🇪 Venezuela" },
  { code: "+54", label: "🇦🇷 Argentina" },
  { code: "+56", label: "🇨🇱 Chile" },
  { code: "+57", label: "🇨🇴 Colombia" },
  { code: "+51", label: "🇵🇪 Peru" },
  { code: "+598", label: "🇺🇾 Uruguay" },
  { code: "+93", label: "🇦🇫 Afghanistan" },
  { code: "+98", label: "🇮🇷 Iran" },
  { code: "+964", label: "🇮🇶 Iraq" },
  { code: "+90", label: "🇹🇷 Turkey" },
  { code: "+353", label: "🇮🇪 Ireland" },
  { code: "+43", label: "🇦🇹 Austria" },
  { code: "+32", label: "🇧🇪 Belgium" },
  { code: "+45", label: "🇩🇰 Denmark" },
  { code: "+372", label: "🇪🇪 Estonia" },
  { code: "+358", label: "🇫🇮 Finland" },
  { code: "+30", label: "🇬🇷 Greece" },
  { code: "+354", label: "🇮🇸 Iceland" },
  { code: "+370", label: "🇱🇹 Lithuania" },
  { code: "+371", label: "🇱🇻 Latvia" },
  { code: "+356", label: "🇲🇹 Malta" },
  { code: "+373", label: "🇲🇩 Moldova" },
  { code: "+377", label: "🇲🇨 Monaco" },
  // { code: "+48", label: "🇵🇱 Poland" },
  { code: "+40", label: "🇷🇴 Romania" },
  { code: "+421", label: "🇸🇰 Slovakia" },
  { code: "+386", label: "🇸🇮 Slovenia" },
];
